version: '3.4'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: archondb
      POSTGRES_USER: archonadmin
      POSTGRES_PASSWORD: psoadminpassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U archonadmin -d archondb && psql -U archonadmin -lqt | cut -d \\| -f 1 | grep -qw archondb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  account:
    build:
      context: .
    command:
      - /usr/bin/account
      - --config
      - /etc/archon
      - --username=testuser
      - --password=testpass
      - --email=test@mail
      - add
    environment:
      ARCHON_DATABASE_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
  server:
    build:
      context: .
    command:
      - /usr/bin/server
      - --config
      - /etc/archon
    environment:
      ARCHON_DATABASE_HOST: postgres
      ARCHON_PATCH_SERVER_PATCH_DIR: ./patches
      ARCHON_CHARACTER_SERVER_PARAMETERS_DIR: ./parameters
      ARCHON_SHIP_SERVER_SHIPGATE_ADDRESS: 0.0.0.0:13000
    ports:
      - 11000:11000
      - 11001:11001
      - 12000:12000
      - 12001:12001
      - 13000:13000
    depends_on:
      postgres:
        condition: service_healthy
