# Server configuration file for Archon.
#
# These defaults should be reasonable for most situations but everything in this file can be
# changed. Don't mess with the ports unless you know what you're doing since the ports defined
# by default are the ones with which the PSOBB client expects to be able to connect (unless
# the executable has been patched to do otherwise).

# Hostname or IP address on which the servers will listen for connections.
hostname: 0.0.0.0
# IP broadcast to clients in the redirect packets.
external_ip: 127.0.0.1
# Maximum number of concurrent connections the server will allow.
max_connections: 3000
# Full path to file to which logs will be written. Blank will write to stdout.
log_file_path: ""
# Minimum level of a log required to be written. Options: debug, info, warn, error
log_level: debug
# X.509 certificate for the shipgate server.
shipgate_certificate_file: "certificate.pem"

web:
  # HTTP endpoint port for publically accessible API endpoints.
  http_port: 10000

database:
  # Database engine (supported: sqlite, postgres).
  engine: sqlite
  # Uncomment the parameters below to use Postgres.
  # engine: postgres
  # host: 127.0.0.1
  # port: 5432
  # name: archondb
  # username: archonadmin
  # password: psoadminpassword
  ## Set to verify-full if the Postgres instance supports SSL.
  # sslmode: disable

patch_server:
  # Port on whith the PATCH server will listen.
  patch_port: 11000
  # Port on which the patch DATA Server will listen.
  data_port: 11001
  # Full (or relative to the current directory) path to the directory containing the patch files.
  patch_dir: "/usr/local/etc/archon/patches"
  # Welcome message displayed on the patch screen.
  welcome_message: "Unconfigured"

login_server:
  # Port on which the LOGIN server will listen.
  port: 12000

character_server:
  # Port on which the CHARACTER server will listen.
  port: 12001
  # Full (or relative to the current directory) path to the directory containing your
  # parameter files (defaults to /usr/local/etc/archon/parameters).
  parameters_dir: "/usr/local/etc/archon/parameters"
  # Scrolling welcome message to display to the user on the ship selection screen.
  scroll_message: "Add a welcome message..."

shipgate_server:
  # Port on which the Shipgate's gRPC server will listen.
  port: 13000
  # Private key file corresponding to shipgate_certificate_file (above).
  ssl_key_file: "key.pem"

ship_server:
  # Port on which the SHIP server will listen.
  port: 15000
  # Name of the ship that will appear in the selection screen.
  name: "Default"
  # Number of block servers to run for this ship.
  num_blocks: 2

block_server:
  # Base block port.
  port: 15001
  # Number of lobbies to create per block.
  num_lobbies: 15

# With the exception of pprof, these should only be enabled for development.
debugging:
  # Enable extra info-providing mechanisms for the server.
  pprof_enabled: true
  # Port on which a pprof server will be started if enabled.
  pprof_port: 4000
  # Log packets to stdout. It's recommended to set log_file_path if enabling this as the
  # server logging output can get intermingled with the packets.
  # TODO: Support logging packets to a file.
  packet_logging_enabled: false
  # Enable database-level query logging.
  database_logging_enabled: false
