package prs

import (
	"bytes"
	"fmt"
	"os"
	"testing"
)

func TestPRS(t *testing.T) {
	// PlyLevelTbl_decompressed was generated by the PRS implementation in C.
	decompressedFile := "testdata/PlyLevelTbl_decompressed.prs"
	wantDecompressed, err := os.ReadFile(decompressedFile)
	if err != nil {
		t.Fatalf("err %v", err)
	}

	testFile := "testdata/PlyLevelTbl.prs"
	golden, err := os.ReadFile(testFile)
	if err != nil {
		t.Fatalf("err %v", err)
	}

	size, err := DecompressSize(golden)
	if err != nil {
		t.Fatalf("decompress size err: %v", err)
	}

	gotDecompressed, err := Decompress(golden, size)
	if err != nil {
		t.Fatalf("decompress err: %v", err)
	}

	if !bytes.Equal(gotDecompressed, wantDecompressed) {
		t.Fatalf("decompressed file does not match expected output")
	}
}

var result []byte

func BenchmarkDecompress(b *testing.B) {
	fmt.Println(os.Getwd())
	testFile := "testdata/PlyLevelTbl.prs"
	golden, err := os.ReadFile(testFile)
	if err != nil {
		b.Fatalf("err %v", err)
	}

	b.ResetTimer()
	b.Run("decompress_with_size", func(b *testing.B) {
		size, err := DecompressSize(golden)
		if err != nil {
			b.Fatalf("decompress size err: %v", err)
		}

		gotDecompressed, err := Decompress(golden, size)
		if err != nil {
			b.Fatalf("decompress err: %v", err)
		}
		result = gotDecompressed
	})
	b.Run("decompress_without_size", func(b *testing.B) {
		size, err := DecompressSize(golden)
		if err != nil {
			b.Fatalf("decompress size err: %v", err)
		}

		gotDecompressed, err := Decompress(golden, size)
		if err != nil {
			b.Fatalf("decompress err: %v", err)
		}
		result = gotDecompressed
	})
}
