name: build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build and test
        run: go build -buildvcs=false -o bin/ ./cmd/*
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Tests
        run: go test ./internal/...

