name: build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: make all
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: make test

