name: build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build and test
        run: make all
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Tests
        run: make test

