name: build
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install required packages
        run: apt-get install -y libc6-dev libpcap-dev
      - name: Build binaries
        run: go build -buildvcs=false -o bin/ ./cmd/*
      - name: Run tests
        run: go test ./internal/...

