name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y libc6-dev libpcap-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
