name: pr-build
on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches-ignore:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the code
        run: go build -v ./cmd/*
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: go test ./cmd/* ./internal/*
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          version: v1.37
          skip-go-installation: true
          args: -E stylecheck -E goimports ./internal/* ./cmd/*
